///|
pub type ApplicationId = Id[ApplicationMarker]

///|
pub type AttachmentId = Id[AttachmentMarker]

///|
pub type AuditLogEntryId = Id[AuditLogEntryMarker]

///|
pub type AutoModerationRuleId = Id[AutoModerationRuleMarker]

///|
pub type ChannelId = Id[ChannelMarker]

///|
pub type CommandId = Id[CommandMarker]

///|
pub type CommandVersionId = Id[CommandVersionMarker]

///|
pub type EmojiId = Id[EmojiMarker]

///|
pub type EntitlementId = Id[EntitlementMarker]

///|
pub type GenericId = Id[GenericMarker]

///|
pub type GuildId = Id[GuildMarker]

///|
pub type IntegrationId = Id[IntegrationMarker]

///|
pub type InteractionId = Id[InteractionMarker]

///|
pub type MessageId = Id[MessageMarker]

///|
pub type RoleId = Id[RoleMarker]

///|
pub type ScheduledEventId = Id[ScheduledEventMarker]

///|
pub type SkuId = Id[SkuMarker]

///|
pub type SubscriptionId = Id[SubscriptionMarker]

///|
pub type SoundboardSoundId = Id[SoundboardSoundMarker]

///|
pub type StageInstanceId = Id[StageInstanceMarker]

///|
pub type StickerId = Id[StickerMarker]

///|
pub type StickerPackId = Id[StickerPackMarker]

///|
pub type TeamId = Id[TeamMarker]

///|
pub type UserId = Id[UserMarker]

///|
pub type WebhookId = Id[WebhookMarker]
