///|
/// Phantom marker types for `Id[M]`. These are empty enums: they have no
/// values and exist only at the type level.
pub enum ApplicationMarker {}

///|
pub enum AttachmentMarker {}

///|
pub enum AuditLogEntryMarker {}

///|
pub enum AutoModerationRuleMarker {}

///|
pub enum ChannelMarker {}

///|
pub enum CommandMarker {}

///|
pub enum CommandVersionMarker {}

///|
pub enum EmojiMarker {}

///|
pub enum EntitlementMarker {}

///|
pub enum GenericMarker {}

///|
pub enum GuildMarker {}

///|
pub enum IntegrationMarker {}

///|
pub enum InteractionMarker {}

///|
pub enum MessageMarker {}

///|
pub enum RoleMarker {}

///|
pub enum ScheduledEventMarker {}

///|
pub enum SkuMarker {}

///|
pub enum SoundboardSoundMarker {}

///|
pub enum StageInstanceMarker {}

///|
pub enum StickerMarker {}

///|
pub enum StickerPackMarker {}

///|
pub enum TeamMarker {}

///|
pub enum UserMarker {}

///|
pub enum WebhookMarker {}
