#!/usr/bin/env python3
"""Generate the `pub extend T with ToJson::{to_json}` declarations.

moonc 0.10.14 deprecates the implicit promotion of trait methods to regular
methods. The module opts out of the promotion (`-implicit_impl_as_method` in
moon.mod) and declares the dot-callable trait methods explicitly instead:

  - `value.to_json()` on every public type that implements `ToJson` — written
    by this script into `src/<pkg>/extends.mbt`, from the `ToJson` impls listed
    in the package's `pkg.generated.mbti`;
  - the few hand-written ones (`Show::to_string`, the limiter/queue/cooldown/
    audio-source traits on their concrete types) sit next to their `impl`.

Usage: scripts/gen_extends.py [--check]
Run `moon info --target native` first when types were added or removed.
With --check nothing is written; exit status is 1 when a file is out of date.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
HEADER = "// Generated by scripts/gen_extends.py. DO NOT EDIT.\n"
TYPE_DECL = re.compile(
    r"^pub(?:\([a-z]+\))? (?:struct|enum|suberror|type) ([A-Z]\w*)")
DERIVE = re.compile(r"derive\(([^)]*)\)")
IMPL = re.compile(r"^pub impl(?:\[[^\]]*\])? ToJson for ([A-Z]\w*)")


def to_json_types(mbti):
    types = set()
    current = None
    for line in mbti.read_text().splitlines():
        if m := TYPE_DECL.match(line):
            current = m.group(1)
        if current and (m := DERIVE.search(line)):
            if "ToJson" in [t.strip() for t in m.group(1).split(",")]:
                types.add(current)
        if m := IMPL.match(line):
            types.add(m.group(1))
    return sorted(types)


def render(types):
    decls = [f"///|\npub extend {t} with ToJson::{{to_json}}\n" for t in types]
    return HEADER + "\n" + "\n".join(decls)


def main():
    check = sys.argv[1:] == ["--check"]
    stale = []
    for mbti in sorted((ROOT / "src").rglob("pkg.generated.mbti")):
        target = mbti.parent / "extends.mbt"
        types = to_json_types(mbti)
        if not types:
            if target.exists():
                stale.append(target)
                if not check:
                    target.unlink()
            continue
        text = render(types)
        if not target.exists() or target.read_text() != text:
            stale.append(target)
            if not check:
                target.write_text(text)
    for path in stale:
        verb = "out of date" if check else "wrote"
        print(f"{verb}: {path.relative_to(ROOT)}")
    return 1 if check and stale else 0


if __name__ == "__main__":
    sys.exit(main())
