graph TD
  app --> framework
  bot --> app
  bot --> cache
  bot --> voice
  bot --> gateway
  http --> model
  http --> ratelimit
  http --> telemetry
  util --> model
  cache --> util
  discord --> bot
  discord --> coordinator
  discord --> endpoint_http
  gateway --> model
  gateway --> queue
  gateway --> telemetry
  framework --> http
  framework --> interaction
  coordinator --> queue
  coordinator --> ratelimit
  interaction --> model
  endpoint_http --> app
  endpoint_http --> verify
